### ISSUE TITLE
Improve main donation button on mobile

### ISSUE THREAD

**Issue by lanort** [charityroyale/webapplication#140]
On mobile, the main donation button might be misleading, especially on duo streams, as it always brings you to the main streamer page of the two:

![image](https://github.com/charityroyale/webapplication/assets/57423/60133ba1-360a-442d-957d-ba03ea24a6be)

Maybe it is better to change this button on mobile to just scroll down if the page is already on a wish page.

**Comment by lanort** [comment]
Von bxrbie:

As a donator I want to be able to only access the donation form of the streamer of my choice when I am on the respective donation page, so that I can donate quicker, easier and without confusion. 

Acceptance criteria:

- the big donate button in the header is not visible on streamer donation pages
- the page jumps to wish description on page load
- desktop + mobile

**Comment by p4dd9** [comment]
As discussed we decided to make it scroll down to the donation form!
